# Site settings
title: Crystal Yip
email: cwt.yip@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio website dedicated to Art, Projects, Videos, Designs 
  and other miscellaneous piece of work.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://crystalyip.me" # the base hostname & protocol for your site
twitter_username: mongtsatsa
github_username:  cwyip

# File inclusion, exclusion, files.
include: [.nojekyll]
exclude: [publish.sh]

# Build settings
markdown: kramdown
